### PR TITLE
Reexport MultivariateStats

### LINKED ISSUE #50: Saving PCAEmbedding to .jld2
It is not possible to load
a `PCAEmbedding` that was saved to a `.jld2` file.

One has to `import MultivariateStats` first
because otherwise `MultivariateStats.PCA` is not a known type and will be reconstructed ( bad).

Likely fixed by exporting `PCA`

### PR DESCRIPTION
**Pull request by JonasIsensee**
Fix error when loading saved `PCAEmbedding`s. closes #50 

Lets see if tests pass.
Simply exporting `PCA` was not enough.
`@reexport MultivariateStats` however did the trick. 
Sadly `@reexport` does not seem to allow something like `@reexport import MultivariateStats: PCA`.

### CODE REVIEW

**Comment by Datseris** [comment]
It should be easy to isolate exactly what is needed to load `PCA` from file. IF `PCA` was not enough, maybe a couple more names are needed?

Polluting the namespace with all the names of `MultivariateStats`, (95% of which are irrelevant) is not a good idea.

**Comment by JonasIsensee** [comment]
See [https://discourse.julialang.org/t/properly-exporting-foreign-types-in-module-for-save-load-jld2/15822?u=jonasisensee]

**Comment by Datseris** [comment]
@JonasIsensee this is important for saving. Do you think _first_ importing `MultivariateStats` is okay for now, or you think I should merge this until https://discourse.julialang.org/t/properly-exporting-foreign-types-in-module-for-save-load-jld2/15822is solved?

**Comment by JonasIsensee** [comment]
It's not important for saving.
It is important for loading.
I've added it into all my scripts already anyway.
No need to hurry

**Comment by Datseris** [comment]
I say we merge this anyway. DOesn't really cost anything...

**Comment by JonasIsensee** [comment]
It does cost something:
`MultivariateStats` also exports a function called `reconstruct`

**Comment by Datseris** [comment]
Alright, did not know that! We obviously can't do that. But you _can_ modify the PR to not reexport MultiVariateStats but instead do:
```
export MultivariateStats.PCA
```

**Comment by JonasIsensee** [comment]
AFAICT This is already done on master.
Sadly that doesn't help because a simple `export` registers the type as `TimeseriesPrediction.PCA`
and not as `MultivariateStats.PCA`.

Anyway... since JLD2 does not seem to be maintained anyhow we could check if BSON has the same problem and choose to ignore this incase it doesn't show up there.

**Pull request closed without merging**
